version: '3.7'

services:
 server_container:
   image: server
   ports:
    - 5002:5000
   networks:
    - jenkins
 client_container:
   image: client
   depends_on:
    - server_container
   ports:
    - 80:80
   networks:
    - jenkins
   links:
    - server_container
   depends_on:
    - server_container
 jenkins_container:
   image: jenkins
   privileged: true
   ports:
    - 50000:50000
    - 8080:8080
   volumes:
    - /home/khalil/jenkins:/var/jenkins_home 
    - /var/run/docker.sock:/var/run/docker.sock
   
networks:
  jenkins:
    driver: bridge

