version: '3.7'

services:
 server_container:
   image: server
   ports:
    - 5000:5000
 jenkins_container:
   image: jenkins
   privileged: true
   ports:
    - 50000:50000
    - 8080:8080
   volumes:
    - /home/khalil/jenkins:/var/jenkins_home 
    - /var/run/docker.sock:/var/run/docker.sock 

